### ISSUE TITLE
Cannot install on windows without node-gyp

### ISSUE THREAD

**Issue by bnolan** [decentraland/commons#50]
When installing on windows without node-gyp, installation fails because of a dependency on `sha3` (a binary npm package). There is a pure javascript implementation of this called [js-sha3](https://github.com/emn178/js-sha3) which might fix this dependency.

The [cli](http://github.com/decentraland/cli) depends on the commons, and because of this dependency (and also `secp256k1`), we are unable to install without requiring a full build environment on windows.

If it's possible to replace these sub-dependencies with pure javascript versions, it will mean that our windows users will only have to install `node` (a 16mb binary) and everything will work. Requiring node-gyp and a build environment means installing python and visual studio.

```
decentraland-commons@0.0.0-development /Users/ben/Contracts/dcl/commons
└─┬ web3-provider-engine@13.6.0 (git+https://github.com/decentraland/provider-engine.git#00eabad4c2a09698e23f44d811aec3e662c11841)
  └─┬ ethereumjs-vm@2.3.2
    └─┬ ethereumjs-util@4.5.0
      └─┬ keccakjs@0.2.1
        └── sha3@1.2.0 
```

**Comment by bnolan** [comment]
This is the install problem I get:

```

C:\Users\user\Contracts\dcl\commons\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )
else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\user\Contracts\dcl\commons\node_modules\sha3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN The package semantic-release is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2018-03-02T02_41_26_198Z-debug.log
```

**Comment by bnolan** [comment]
Ok, it's possible to install commons using [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools), so although a pure javascript implementation would be preferable - this works.

**Comment by XBITSwitzerland** [comment]
So what is the solution to this error? I cant install anything with npm
